### ISSUE TITLE
What is the right way to download files without running out of memory?

### ISSUE THREAD

**Issue by videoguy** [jfrog/artifactory-client-java#113]
We use artifactory java bindings from this project to download content from our artifactory. I am running into outofmemory when downloading a file with size 460MB. Below is the exception trace.

The code snippet that implements the download is below.

```

            try
            {
                if (null == fileHandle)
                    fileHandle = aRepo.download(remotePath);
                if (null == fileHandle)
                {
                    Logger.getGlobal().log(Level.SEVERE, "Unable to get download artifact handle for remote path: {0}", remotePath);
                    bResult = false;
                    continue;
                }                    
                
                InputStream in = fileHandle.doDownload();

                if (null == in)
                {
                    Logger.getGlobal().log(Level.SEVERE, "Unable to download remote file: {0}", remotePath);
                    bResult = false;
                }
                else
                {
                    File fileOut = new File(localPath);

                    if (null != fileOut.getParentFile())
                        fileOut.getParentFile().mkdirs();
                    fileOut.createNewFile();
                    OutputStream out = new FileOutputStream(fileOut);
                    IOUtils.copy(in, out);
                    IOUtils.closeQuietly(in);
                    IOUtils.closeQuietly(out);
                    bResult = true;
                    break;
                } 
            }
            catch (Throwable ex)
            {
                bResult = false;
                if (!propagateExceptionsUp)
                    Logger.getGlobal().log(Level.SEVERE, "Exception while downloading "+remotePath+", retrying...", ex);
                else
                    throw ex;                    
            }


```
++++Exception+++++++++++++

java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at org.codehaus.groovy.runtime.IOGroovyMethods.leftShift(IOGroovyMethods.java:219)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.leftShift(DefaultGroovyMethods.java:14058)
        at groovyx.net.http.HTTPBuilder.defaultSuccessHandler(HTTPBuilder.java:620)
        at groovyx.net.http.RESTClient.defaultSuccessHandler(RESTClient.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:952)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.RESTClient.get(RESTClient.java:119)
        at groovyx.net.http.RESTClient$get.call(Unknown Source)
        at org.jfrog.artifactory.client.impl.ArtifactoryImpl.getInputStream(ArtifactoryImpl.groovy:146)
        at org.jfrog.artifactory.client.impl.ArtifactoryImpl.getInputStream(ArtifactoryImpl.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:187)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)

**Comment by achappelle** [comment]
Did anyone find a  solution for this?  I'm seeing the same issue.

**Comment by romangurevitch** [comment]
@achappelle, 
Currently the Artifactory Java client uses groovy's RESTClient for all REST API calls.
We are working to improve and change the HTTP client which will solve many problems including this one. 
We intend to introduce this change soon,  will keep you posted.

**Comment by Skyr** [comment]
This problem hasn't been addressed yet? We're using the latest artifactory-java-client-services (v2.5.2), when downloading a large file from Artifactory (trying to obtain an InputStream via `artifactory.repository(repo).download(path).doDownload()`) we get a very similar exception:

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at org.codehaus.groovy.runtime.IOGroovyMethods.leftShift(IOGroovyMethods.java:219)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.leftShift(DefaultGroovyMethods.java:14123)
	at groovyx.net.http.HTTPBuilder.defaultSuccessHandler(HTTPBuilder.java:620)
	at groovyx.net.http.RESTClient.defaultSuccessHandler(RESTClient.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1073)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
	at groovyx.net.http.RESTClient.get(RESTClient.java:119)
	at groovyx.net.http.RESTClient$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.jfrog.artifactory.client.impl.ArtifactoryImpl.getInputStream(ArtifactoryImpl.groovy:146)
	at org.jfrog.artifactory.client.impl.ArtifactoryImpl.getInputStream(ArtifactoryImpl.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
