### ISSUE TITLE
Artifactory.createClient() throws exception even after correct jackson dependency

### ISSUE THREAD

**Issue by adhunikgupta** [jfrog/artifactory-client-java#149]
I'm getting the following error when I try to instantiate the Artifactory client.

`Artifactory artifactory = ArtifactoryClient.create(artifactoryUrl, "", "");`

Whenever i run my code independently in a main function , it doesnt throw an exception and works properly. But when i run it in a MVC architecture (WebApp) it stops working and throws the following error :

No signature of method: com.fasterxml.jackson.databind.ObjectMapper.addMixIn() is applicable for argument types: (java.lang.Class, java.lang.Class) values: [interface org.jfrog.artifactory.client.model.Repository, interface org.jfrog.artifactory.client.impl.jackson.RepositoryMixIn]

And I get the error stack trace below when it executes. I have done extensive research on this issue, and I have not found anyone with a similar error except for the ones referenced in this issue: https://github.com/JFrogDev/artifactory-client-java/issues/85

The above issue was because of wrong dependencies. I'm getting the 2.4.6 version of the artifactory client and the jackson libraries as well.

`groovy.lang.MissingMethodException: No signature of method: com.fasterxml.jackson.databind.ObjectMapper.addMixIn() is applicable for argument types: (java.lang.Class, java.lang.Class) values: [interface org.jfrog.artifactory.client.model.Repository, interface org.jfrog.artifactory.client.impl.jackson.RepositoryMixIn] 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.jfrog.artifactory.client.impl.ArtifactoryImpl.(ArtifactoryImpl.groovy:46) 14:04:21,684 +0000 INFO [stdout] (default task-22) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 14:04:21,684 +0000 INFO [stdout] (default task-22) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 14:04:21,684 +0000 INFO [stdout] (default task-22) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 14:04:21,684 +0000 INFO [stdout] (default task-22) at java.lang.reflect.Constructor.newInstance(Unknown Source) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102) 14:04:21,684 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57) 14:04:21,692 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182) 14:04:21,692 +0000 INFO [stdout] (default task-22) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194) 14:04:21,692 +0000 INFO [stdout] (default task-22) at org.jfrog.artifactory.client.ArtifactoryClient.create(ArtifactoryClient.groovy:95) 14:04:21,693 +0000 INFO [stdout] (default task-22) at org.jfrog.artifactory.client.ArtifactoryClient.create(ArtifactoryClient.groovy) 14:04:21,693 +0000 INFO [stdout] (default task-22) at com.xyz.abc.utils.WGArtifactoryUtils.getFiles(WGArtifactoryUtils.java:41) 14:04:21,693 +0000 INFO [stdout] (default task-22) at com.xyz.abc.lakshya.controllers.ListPlController.findFilesFromArtifactory(ListPlController.java:196) 14:04:21,693 +0000 INFO [stdout] (default task-22) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 14:04:21,694 +0000 INFO [stdout] (default task-22) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 14:04:21,695 +0000 INFO [stdout] (default task-22) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 14:04:21,695 +0000 INFO [stdout] (default task-22) at java.lang.reflect.Method.invoke(Unknown Source) 14:04:21,695 +0000 INFO [stdout] (default task-22) at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215) 14:04:21,696 +0000 INFO [stdout] (default task-22) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) 14:04:21,696 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) 14:04:21,696 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749) 14:04:21,696 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:690) 14:04:21,697 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83) 14:04:21,697 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945) 14:04:21,697 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:876) 14:04:21,698 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) 14:04:21,698 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863) 14:04:21,698 +0000 INFO [stdout] (default task-22) at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) 14:04:21,699 +0000 INFO [stdout] (default task-22) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837) 14:04:21,699 +0000 INFO [stdout] (default task-22) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) 14:04:21,699 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86) 14:04:21,699 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130) 14:04:21,699 +0000 INFO [stdout] (default task-22) at com.adobe.jobcloud.spring.security.filters.SessionTimeoutFilter.doFilter(SessionTimeoutFilter.java:65) 14:04:21,699 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) 14:04:21,700 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) 14:04:21,700 +0000 INFO [stdout] (default task-22) at com.adobe.jobcloud.ws.security.filters.UiResponseFilter.doFilterInternal(UiResponseFilter.java:55) 14:04:21,700 +0000 INFO [stdout] (default task-22) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) 14:04:21,700 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) 14:04:21,700 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) 14:04:21,700 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) 14:04:21,700 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) 14:04:21,700 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) 14:04:21,701 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,701 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) 14:04:21,701 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,701 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) 14:04:21,701 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,702 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) 14:04:21,702 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,702 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) 14:04:21,702 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,703 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) 14:04:21,703 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,703 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) 14:04:21,703 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,704 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199) 14:04:21,704 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,704 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) 14:04:21,704 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,705 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50) 14:04:21,705 +0000 INFO [stdout] (default task-22) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108) 14:04:21,705 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,705 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) 14:04:21,705 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) 14:04:21,706 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) 14:04:21,706 +0000 INFO [stdout] (default task-22) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) 14:04:21,706 +0000 INFO [stdout] (default task-22) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) 14:04:21,706 +0000 INFO [stdout] (default task-22) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) 14:04:21,706 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) 14:04:21,707 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) 14:04:21,707 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) 14:04:21,707 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) 14:04:21,707 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) 14:04:21,709 +0000 INFO [stdout] (default task-22) at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) 14:04:21,709 +0000 INFO [stdout] (default task-22) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 14:04:21,709 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) 14:04:21,710 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) 14:04:21,710 +0000 INFO [stdout] (default task-22) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 14:04:21,711 +0000 INFO [stdout] (default task-22) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) 14:04:21,711 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) 14:04:21,716 +0000 INFO [stdout] (default task-22) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) 14:04:21,716 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) 14:04:21,716 +0000 INFO [stdout] (default task-22) at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) 14:04:21,717 +0000 INFO [stdout] (default task-22) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 14:04:21,719 +0000 INFO [stdout] (default task-22) at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77) 14:04:21,719 +0000 INFO [stdout] (default task-22) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167) 14:04:21,720 +0000 INFO [stdout] (default task-22) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) 14:04:21,720 +0000 INFO [stdout] (default task-22) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761) 14:04:21,720 +0000 INFO [stdout] (default task-22) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 14:04:21,720 +0000 INFO [stdout] (default task-22) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 14:04:21,720 +0000 INFO [stdout] (default task-22) at java.lang.Thread.run(Unknown Source)`

I am using the following versions:

Artifactory : 2.4.6

Jackson(databind,annotations,core) : 2.4.6

**Comment by AntonFagerberg** [comment]
I started hitting this also today for no good reason.

But when I dug into the jackson code, I can see that `addMixIn` was added in `2.5` so Jackson `2.4.6` shouldn't ever have worked?

I haven't done more digging but to me this sounds like an incorrect dependency version shipped with the Artifactory client.

**Comment by EMCP** [comment]
Just today I loaded up the jfrog artifactory client `v2.8.6` 

```
        <dependency>
            <groupId>org.jfrog.artifactory.client</groupId>
            <artifactId>artifactory-java-client-services</artifactId>
            <version>2.8.6</version>
        </dependency>
```

it seems to be giving similar errors when running the client 

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
	at org.jfrog.artifactory.client.impl.util.Util.responseToObject(Util.java:36)
	at org.jfrog.artifactory.client.impl.ArtifactoryImpl.put(ArtifactoryImpl.java:338)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.jfrog.artifactory.client.impl.UploadableArtifactImpl.uploadContent(UploadableArtifactImpl.groovy:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at org.jfrog.artifactory.client.impl.UploadableArtifactImpl.uploadContent(UploadableArtifactImpl.groovy:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at org.jfrog.artifactory.client.impl.UploadableArtifactImpl.doUpload(UploadableArtifactImpl.groovy:60)
	at artifactoryTester.main(artifactoryTester.java:15)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 34 more
```
