### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method: org.jfrog.artifactory.client.impl.ArtifactBase.withProperty() 

### ISSUE THREAD

**Issue by vickyrare** [jfrog/artifactory-client-java#385]
**Describe the bug**
groovy.lang.MissingMethodException: No signature of method: org.jfrog.artifactory.client.impl.ArtifactBase.withProperty() 

**To Reproduce**
Try to set the property and then upload.

 Map<String, String> attributes = artifactoryUploadItem.getAttributes();

 attributes.forEach((k, v) -> uploadableArtifact.withProperty(k, v));

 File file = uploadableArtifact.doUpload();

**Expected behavior**

**Screenshots**

**Versions**
- Artifactory Java Client version: 2.9.2
- Operating system: Mac OS X
- Artifactory Version: EnterpriseX license 7.63.14

**Additional context**
We have recently upgraded from Micronaut 3 to Micronaut 4.
The groovy was updated from 3.0.13 to 4.0.20

groovy.lang.MissingMethodException: No signature of method: org.jfrog.artifactory.client.impl.ArtifactBase.withProperty() is applicable for argument types: (String, String) values: [artifact-hash, 5586d855ba242032a3aad0216a74ac61c18288077aed217589baec3729f8f9a5]
Possible solutions: withProperty(java.lang.String, [Ljava.lang.Object;), withProperty(java.lang.String, java.lang.Object), hasProperty(java.lang.String)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:148)
	at org.jfrog.artifactory.client.impl.UploadableArtifactImpl.withProperty(UploadableArtifactImpl.groovy:140)
	at com.oracle.swaservices.common.artifactory.DefaultArtifactoryUploadService.lambda$upload$0(DefaultArtifactoryUploadService.java:52)

**Comment by dmeibusch** [comment]
Workaround: separately set properties after upload of the artifact rather than using the problematic Groovy overloaded `withProperty` method that can not be handled by newer Groovy runtimes.

Downsides: two calls vs one call to repository.
